src/Entity/Station.php
<?php

namespace App\Entity;

use App\Repository\StationRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: StationRepository::class)]
class Station
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $name;

    #[ORM\Column(type: 'float')]
    private $emplacement_lat;

    #[ORM\Column(type: 'float')]
    private $emplacement_lon;

    #[ORM\OneToMany(mappedBy: 'station', targetEntity: Velo::class)]
    private $velos;

    public function __construct()
    {
        $this->velos = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getEmplacementLat(): ?float
    {
        return $this->emplacement_lat;
    }

    public function setEmplacementLat(float $emplacement_lat): self
    {
        $this->emplacement_lat = $emplacement_lat;

        return $this;
    }

    public function getEmplacementLon(): ?float
    {
        return $this->emplacement_lon;
    }

    public function setEmplacementLon(float $emplacement_lon): self
    {
        $this->emplacement_lon = $emplacement_lon;

        return $this;
    }

    /**
     * @return Collection|Velo[]
     */
    public function getVelos(): Collection
    {
        return $this->velos;
    }

    public function addVelo(Velo $velo): self
    {
        if (!$this->velos->contains($velo)) {
            $this->velos[] = $velo;
            $velo->setStation($this);
        }

        return $this;
    }

    public function removeVelo(Velo $velo): self
    {
        if ($this->velos->removeElement($velo)) {
            // set the owning side to null (unless already changed)
            if ($velo->getStation() === $this) {
                $velo->setStation(null);
            }
        }

        return $this;
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use App\Repository\StationRepository;
use App\Repository\VeloRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;

class HomeController extends AbstractController
{
    #[Route('/', name: 'home')]
    public function index(StationRepository $station_repo, VeloRepository $velo_repo, AuthenticationUtils $authenticationUtils): Response
    {
        if ($authenticationUtils->getLastUsername()) {
            $stations = $station_repo->findAll();
            $velos = $velo_repo->findAll();

            return $this->render('home/index.html.twig', [
                'controller_name' => 'HomeController',
                'stations' => $stations,
                'velos' => $velos
            ]);
        } else {
            return $this->redirectToRoute('app_login');
        }

    }

    #[Route('/reservation', name: "reservation")]
    public function reservation() {
        $this->addFlash('reussi', "Vous avez bien reserver");
        $this->redirectToRoute('home');
    }
}

templates/home/index.html.twig
{% extends 'base.html.twig' %}


{% block body %}

    {% for message in app.flashes('success') %}
        <div class="col-md-6 bg-success p-4 rounded mx-auto text-center text-white mb-3">
            {{ message }}
        </div>
    {% endfor %}

    <div style="height: 85vh;width: 100vw;z-index: 99" id="map"></div>

    <script type="text/javascript">
        let map = L.map('map').setView([48.85780, 2.34111], 12);

        let geojsonFeature = {
            "type": "FeatureCollection",
            "features": [
                {% for station in stations %}
                {
                    "type": "Feature",
                    "properties": {
                        "name": "{{ station.name }}",
                        "amenity": "Station de vélo",
                        {% if station.velos.count is same as(0) %}
                        "popupContent": "Il n'y as plus de vélos disponible dans la station {{ station.name }}",
                        {% else %}
                        "popupContent": '{{ station.name }} <br> <br> {{ station.velos.count }} vélos disponible <br><br> <div style="display:flex;justify-content:center;"> <a style="color: white" href="{{ path('reservation') }}" class="btn btn-success">Louer un vélo</a> </div>',
                        {% endif %}
                        "marker-color": "#0433ff",
                        "marker-size": "medium",
                        "marker-symbol": "bicycle"
                    },
                    "geometry": {
                        "type": "Point",
                        "coordinates": [{{ station.emplacementLon }}, {{ station.emplacementLat }}]
                    }
                },
                {% endfor %}
            ]
        }
        function onEachFeature(feature, layer) {
            // does this feature have a property named popupContent?
            if (feature.properties && feature.properties.popupContent) {
                layer.bindPopup(feature.properties.popupContent);
            }

            return feature.properties.show_on_map;
        }

        //L.geoJSON(geojsonFeature).addTo(map);
        L.geoJSON(geojsonFeature, {onEachFeature: onEachFeature}).addTo(map);

        L.tileLayer('https://api.mapbox.com/styles/v1/{id}/tiles/{z}/{x}/{y}?access_token={accessToken}', {
            attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors, Imagery © <a href="https://www.mapbox.com/">Mapbox</a>',
            maxZoom: 18,
            id: 'mapbox/streets-v11',
            tileSize: 512,
            zoomOffset: -1,
            accessToken: 'sk.eyJ1IjoiamFyY2hhbWJhdWx0IiwiYSI6ImNrenBtM3l6ZTAyMmEyeWxqbmFydTg5ZnMifQ.I0cWGny1kddLYzR86KdRHg'
        }).addTo(map);
    </script>

    <div style="width: 100vw;height: 15vh;position: absolute;bottom: 0;left:0;background-color: white;border: 1px solid lightgrey">
        <nav>
            <ul class="mt-3 d-flex justify-content-center">
                <a class="btn btn-danger" href="{{ path('app_logout') }}">Déconnexion</a>
            </ul>
        </nav>
    </div>
{% endblock %}